version: '3.8'

services:
  springboot:
    image: pmmanoj1997/mavenwebapp:1
    container_name: mavenwebapp-container
    restart: always
    ports:
      - "9090:8080"
    networks:
      - mavenappbridge

networks:
  mavenappbridge:
    driver: bridge

